/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;


/**
 *
 * @author GWAPOKA
 */
public class profile extends javax.swing.JFrame {

    /**
     * Creates new form profile
     */
    public profile() {
        if (student.session.fullname == null || student.session.fullname.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Access Denied! Please login first.");
        new login().setVisible(true);
        this.dispose();
        return;
    }        
        initComponents();
        loadSessionData();
        fullname.setText(" Role: " + session.fullname);
        usertype.setText(" Name: " + session.usertype);
        email.setText(" Email: " +  session.email);
        profileImage.setText( session.profileImage);
    }
    private void loadSessionData() {

    fullname.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    // 1. Check if the session is empty
    if (student.session.fullname == null || student.session.fullname.isEmpty()) {
        fullname.setText("No user logged in");
        return;
    }

    // Just let the labels read what is ALREADY in the session:
    fullname.setText(" Name: " + student.session.fullname);
    usertype.setText(" Role: " + student.session.usertype);
    email.setText(" Email: " + student.session.email);
    email.setText(" Email: " + student.session.email);
    profileImage.setText(student.session.profileImage);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        profileImage = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("back");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 90, 500);

        profileImage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        profileImage.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(profileImage);
        profileImage.setBounds(380, 50, 190, 160);

        fullname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fullname.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(fullname);
        fullname.setBounds(330, 220, 290, 50);

        usertype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usertype.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(usertype);
        usertype.setBounds(330, 270, 290, 50);

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(email);
        email.setBounds(330, 320, 290, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(730, 10, 103, 31);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    student.homepage home = new student.homepage();
    home.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to log out?", "Logout", 
            javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // 2. Clear the Session data
        student.session.fullname = null;
        student.session.usertype = null;
        student.session.email = null;
        student.session.profileImage = null;

        // 3. Open the Login window
        login log = new login();
        log.setVisible(true);

        // 4. Close the Profile window
        this.dispose();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email;
    private javax.swing.JLabel fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel profileImage;
    private javax.swing.JLabel usertype;
    // End of variables declaration//GEN-END:variables
}
