/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;

import admin.Studentmanagement;

/**
 *
 * @author PC 12
 */
public class StudentRegister extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegister
     */
    public StudentRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        u_fname = new javax.swing.JTextField();
        u_studentid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        u_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        u_password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        u_reenterpassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(400, 10, 77, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 1268);

        jLabel6.setText("User Name");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(640, 200, 80, 14);

        u_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_fnameActionPerformed(evt);
            }
        });
        jDesktopPane1.add(u_fname);
        u_fname.setBounds(640, 220, 230, 30);
        jDesktopPane1.add(u_studentid);
        u_studentid.setBounds(640, 160, 230, 40);

        jLabel4.setText("Student ID");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(640, 140, 80, 14);

        u_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_emailActionPerformed(evt);
            }
        });
        jDesktopPane1.add(u_email);
        u_email.setBounds(640, 270, 230, 30);

        jLabel5.setText("Email");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(640, 250, 40, 20);

        jLabel3.setText("Password");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(640, 300, 46, 14);
        jDesktopPane1.add(u_password);
        u_password.setBounds(640, 320, 230, 32);

        jLabel2.setText("Re Enter password");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(640, 350, 91, 14);

        u_reenterpassword.setToolTipText("");
        jDesktopPane1.add(u_reenterpassword);
        u_reenterpassword.setBounds(640, 370, 230, 30);

        jButton1.setText("Save");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(720, 410, 80, 30);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void u_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_fnameActionPerformed

    private void u_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    login lg = new login();
    lg.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    String name = u_fname.getText();
    String email = u_email.getText();
    String uid = u_studentid.getText();
    String upass = u_password.getText();
    String upass2 = u_reenterpassword.getText();

    // Basic Validation
    if(name.isEmpty() || email.isEmpty() || uid.isEmpty() || upass.isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "All fields are required!");
        return;
    }

    if(!upass.equals(upass2)){
        javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match!");
        return;
    }

    try {
        // 1. Use your existing config connection
        java.sql.Connection conn = config.spconfig.connectDB();

        // 2. Updated SQL: Added 'role' to the columns and one more '?' to values
        String sql = "INSERT INTO users (name, email, student_id, role, password, re_enter_password) VALUES (?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        
        pstmt.setString(1, name);
        pstmt.setString(2, email);
        pstmt.setString(3, uid);
        pstmt.setString(4, "Student");
        pstmt.setString(5, upass);
        pstmt.setString(6, upass2);

        pstmt.executeUpdate();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Registration Successful! Role assigned: Student.");
        
        pstmt.close();
        conn.close();
        
        // Return to login
        student.login log = new student.login(); 
        log.setVisible(true);
        this.dispose(); 

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField u_email;
    private javax.swing.JTextField u_fname;
    private javax.swing.JTextField u_password;
    private javax.swing.JTextField u_reenterpassword;
    private javax.swing.JTextField u_studentid;
    // End of variables declaration//GEN-END:variables
}
