/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;

/**
 *
 * @author PC 12
 */
public class Studyload extends javax.swing.JFrame {

    /**
     * Creates new form Studyload
     */
    public Studyload() {
    if (student.session.fullname == null || student.session.fullname.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Access Denied! Please login first.");
        new login().setVisible(true);
        this.dispose();
        return;
    }
    initComponents();
    // Center the window
    this.setLocationRelativeTo(null);
    
    // Set user info from session
    name.setText(student.session.fullname);
    user.setText(student.session.usertype);
    
    // Load the transaction table immediately
    showMyEnrolledSubjects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Portal");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 130, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("StudyLoad");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 160, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconify-icon.png"))); // NOI18N
        jDesktopPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setText("Profile");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 220, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SVG (1).png"))); // NOI18N
        jDesktopPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Study Load");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconify-icon (4).png"))); // NOI18N
        jDesktopPane1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("My Classes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 220, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconify-icon (5).png"))); // NOI18N
        jDesktopPane1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 50));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Grades");
        jDesktopPane1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconify-icon (6).png"))); // NOI18N
        jDesktopPane1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Announcement");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 260, 500));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 130, 20));

        user.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 80, 10));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Register for Subjects");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jDesktopPane1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 630, 340));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        profile prof = new profile();
        prof.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // 1. Create the target frame (using 'homepage' based on your folder image)
    homepage home = new homepage(); 
    
    // 2. Show the announcement/home screen
    home.setVisible(true);
    
    // 3. Close the current Studyload frame
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String sName = student.session.fullname;
    
    // 1. Fetch available subjects AND their assigned teachers from the database
    // We use a Map to store Title as Key and Teacher as Value
    java.util.Map<String, String> subjectMap = new java.util.HashMap<>();
    String sqlFetch = "SELECT title, assigned_teache FROM subjects"; 
    
    try (java.sql.Connection conn = config.spconfig.connectDB();
         java.sql.PreparedStatement pstmt = conn.prepareStatement(sqlFetch);
         java.sql.ResultSet rs = pstmt.executeQuery()) {
        
        while (rs.next()) {
            subjectMap.put(rs.getString("title"), rs.getString("assigned_teache"));
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading subjects: " + e.getMessage());
        return;
    }

    if (subjectMap.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No subjects found.");
        return;
    }

    // 2. Display the dropdown menu
    Object[] selectionValues = subjectMap.keySet().toArray();
    String sSubject = (String) javax.swing.JOptionPane.showInputDialog(
                        this,
                        "Choose a subject to register:",
                        "Available Subjects",
                        javax.swing.JOptionPane.QUESTION_MESSAGE,
                        null,
                        selectionValues,
                        selectionValues[0]);

    // 3. If a subject was selected, save it with the teacher's name
    if (sSubject != null && !sSubject.trim().isEmpty()) {
        String sTeacher = subjectMap.get(sSubject); // Get the teacher for the selected subject
        config.spconfig conf = new config.spconfig();
        
        // Update your enrollment SQL to include the teacher
        String sqlInsert = "INSERT INTO enrollments (student_name, subject_title, assigned_teache) VALUES (?, ?, ?)";
        conf.addRecord(sqlInsert, sName, sSubject, sTeacher); 
        
        javax.swing.JOptionPane.showMessageDialog(this, "Registered for " + sSubject + " under " + sTeacher);
        
        showMyEnrolledSubjects(); // Refresh your table
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showMyEnrolledSubjects() {
    config.spconfig conf = new config.spconfig();
    String sql = "SELECT enrollment_id AS 'Ref ID', subject_title AS 'Subject', "
               + "assigned_teache AS 'Teacher', date_enrolled AS 'Date Enrolled' "
               + "FROM enrollments WHERE student_name = '" + student.session.fullname + "'";
    
    conf.displayData(sql, jTable1);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studyload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studyload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studyload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studyload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studyload().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
