/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 *
 * @author Jon-Jon
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public AddUser() {
    if (student.session.fullname == null || !"Program Head".equals(student.session.usertype)) {
        javax.swing.JOptionPane.showMessageDialog(null, "Unauthorized access! Admin login required.");
        new student.login().setVisible(true);
        this.dispose();
        return;
    }
    initComponents(); 
    this.setLocationRelativeTo(null); 
    role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Student", "Teacher"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        role = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ReEnterPassword = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("User ID");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));
        jDesktopPane1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 160, 30));

        Name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Name.setText("User Name");
        jDesktopPane1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));
        jDesktopPane1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Email");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));
        jDesktopPane1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 160, 30));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Role" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        jDesktopPane1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Role");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Password");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));
        jDesktopPane1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Re Enter Password");
        jDesktopPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));
        jDesktopPane1.add(ReEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 160, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, 30));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Studentmanagement sm = new Studentmanagement();
    sm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String userId = id.getText().trim();
    String userName = jTextField1.getText().trim();
    String userEmail = email.getText().trim();
    String userPass = password.getText();
    String rePass = ReEnterPassword.getText();
    String selectedRole = role.getSelectedItem().toString();

    // 1. Validation
    if (userId.isEmpty() || userName.isEmpty() || userEmail.isEmpty() || userPass.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "All fields (including User ID) are required!");
        return;
    }

    if (!userPass.equals(rePass)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match!");
        return;
    }

    config.spconfig conf = new config.spconfig();

    // 2. Routing based on Selected Role
    if (selectedRole.equals("Admin")) {
        // Admins are stored in the 'admin' table 
        String sql = "INSERT INTO admin (username, password, email, role) VALUES (?, ?, ?, ?)";
        conf.addRecord(sql, userName, userPass, userEmail, "Program Head");
        
    } else if (selectedRole.equals("Teacher")) {
        // We must include 'role' and 're_enter_password' to satisfy the NOT NULL constraint
        // Note the space in " name" to match your specific database schema 
        String sql = "INSERT INTO teacher (teacher_id, \" name\", email, role, password, re_enter_password) VALUES (?, ?, ?, ?, ?, ?)";
        
        // Passing 6 values to match the 6 question marks above
        conf.addRecord(sql, userId, userName, userEmail, "Teacher", userPass, rePass);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Teacher account created successfully!");
        
    } else {
        // Students are stored in the 'users' table [cite: 32]
        String sql = "INSERT INTO users (student_id, name, email, role, password, re_enter_password) VALUES (?, ?, ?, ?, ?, ?)";
        conf.addRecord(sql, userId, userName, userEmail, "Student", userPass, rePass);
        javax.swing.JOptionPane.showMessageDialog(this, "Student account created successfully!");
    }
    clearFields();
}

    private void clearFields() {
    id.setText("");
    jTextField1.setText("");
    email.setText("");
    password.setText("");
    ReEnterPassword.setText("");
    role.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed

    }//GEN-LAST:event_roleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JTextField ReEnterPassword;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> role;
    // End of variables declaration//GEN-END:variables
}
