/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.spconfig;
import student.login;
import student.session;

/**
 *
 * @author NJ
 */
public class Studentmanagement extends javax.swing.JFrame {

    /**
     * Creates new form Studentmanagement
     */
    public Studentmanagement() {
    if (student.session.fullname == null || !"Program Head".equals(student.session.usertype)) {
        javax.swing.JOptionPane.showMessageDialog(null, "Unauthorized access! Admin login required.");
        new student.login().setVisible(true);
        this.dispose();
        return;
    }
    initComponents(); 
    lblname.setText(student.session.fullname);
    name.setText(student.session.usertype);
    showStudentData();
    }
    public void showStudentData() {
    config.spconfig conf = new config.spconfig();
        String sql = "SELECT student_id AS 'ID', name AS 'Name', email AS 'Email', role AS 'Role' FROM users "
                   + "UNION ALL "
                   + "SELECT 'ADMIN' AS 'ID', username AS 'Name', email AS 'Email', role AS 'Role' FROM admin";
        
        conf.displayData(sql, StudentTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        subjectmanagement = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        SearchBar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Portal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconify-icon.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 40, -1, -1));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        subjectmanagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subjectmanagement.setText("Subject Management");
        subjectmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectmanagementActionPerformed(evt);
            }
        });
        jDesktopPane1.add(subjectmanagement);
        subjectmanagement.setBounds(60, 190, 230, 31);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 51, 0));
        jButton10.setText("Logout");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton10);
        jButton10.setBounds(220, 460, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Add User");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton3);
        jButton3.setBounds(840, 90, 130, 23);

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(StudentTable);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(460, 180, 510, 270);

        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(SearchBar);
        SearchBar.setBounds(460, 130, 160, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Archive");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton5);
        jButton5.setBounds(60, 250, 230, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("User Management");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(60, 130, 230, 31);

        lblname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblname.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(lblname);
        lblname.setBounds(820, 10, 170, 30);

        name.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(name);
        name.setBounds(820, 40, 100, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 500);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(840, 120, 130, 23);

        delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delete.setText("Remove Student");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jDesktopPane1.add(delete);
        delete.setBounds(840, 150, 130, 23);

        SEARCH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jDesktopPane1.add(SEARCH);
        SEARCH.setBounds(630, 140, 77, 23);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        String search = SearchBar.getText();
        config.spconfig conf = new config.spconfig();

        String sql = "SELECT * FROM ("
        + "  SELECT student_id AS 'ID', name AS 'Name', email AS 'Email', role AS 'Role' FROM users "
        + "  UNION ALL "
        + "  SELECT 'ADMIN' AS 'ID', username AS 'Name', email AS 'Email', role AS 'Role' FROM admin"
        + ") AS combined "
        + "WHERE Name LIKE '%" + search + "%' OR Email LIKE '%" + search + "%'";

        conf.displayData(sql, StudentTable);

        conf.displayData(sql, StudentTable);
    }//GEN-LAST:event_SEARCHActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int row = StudentTable.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a student to delete.");
        } else {
            String id = StudentTable.getValueAt(row, 0).toString();
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete Student ID: " + id + "?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                config.spconfig conf = new config.spconfig();
                // Assuming your column in DB is 'student_id'
                String sql = "DELETE FROM users WHERE student_id = ?";
                // You might need to add a generic executeQuery method in spconfig or use connection here
                try {
                    java.sql.Connection conn = config.spconfig.connectDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, id);
                    pst.executeUpdate();
                    showStudentData(); // Refresh table
                } catch (Exception e) { System.out.println(e); }
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        update up = new update();
        up.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // Calling the same logic as the button
        SEARCHActionPerformed(evt);
    }//GEN-LAST:event_SearchBarActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        // 2. Check if the user clicked "Yes"
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            // Go back to login screen
            login lg = new login();
            lg.setVisible(true);

            // Close this Student Management window
            this.dispose();
        }
        // If they click "No", the dialog simply closes and nothing happens
    }//GEN-LAST:event_jButton10ActionPerformed

    private void subjectmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectmanagementActionPerformed
        // Create the new Subject Management Frame
        SubjectManagement sm = new SubjectManagement();
        sm.setVisible(true);

        // Close the current Student Management Frame
        this.dispose();
    }//GEN-LAST:event_subjectmanagementActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AddUser au = new AddUser();
        au.setVisible(true);
        this.dispose(); // Closes Student Management and opens Add User
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentmanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentmanagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SEARCH;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel name;
    private javax.swing.JButton subjectmanagement;
    // End of variables declaration//GEN-END:variables
}
