/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import student.login;

/**
 *
 * @author PC 12
 */
public class SubjectManagement extends javax.swing.JFrame {

    /**
     * Creates new form SubjectManagement
     */
    public SubjectManagement() {
    if (student.session.fullname == null || !"Program Head".equals(student.session.usertype)) {
        javax.swing.JOptionPane.showMessageDialog(null, "Unauthorized access! Admin login required.");
        new student.login().setVisible(true);
        this.dispose();
        return;
    }
    initComponents();
    // Load session data
    lblname.setText(student.session.fullname);
    name.setText(student.session.usertype);
    // Refresh table on startup
    showSubjectData();
}

public void showSubjectData() {
// SQL matches your database columns: subject_id, code, title, units, assigned_teache, semester, school_year
    String sql = "SELECT subject_id AS 'ID', code AS 'Code', title AS 'Title', "
               + "units AS 'Units', assigned_teache AS 'Teacher', "
               + "semester AS 'Semester', school_year AS 'Year' FROM subjects";
    
    config.spconfig conf = new config.spconfig();
    
    // This will automatically populate your StudentTable with the 7 columns above
    conf.displayData(sql, StudentTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton10 = new javax.swing.JButton();
        subjectmanagement = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SearchBar = new javax.swing.JTextField();
        SEARCH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 51, 0));
        jButton10.setText("Logout");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 120, 30));

        subjectmanagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subjectmanagement.setText("Subject Management");
        subjectmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectmanagementActionPerformed(evt);
            }
        });
        jDesktopPane1.add(subjectmanagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 230, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("User Management");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 230, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Portal");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconify-icon.png"))); // NOI18N
        jDesktopPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        name.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 100, 10));

        lblname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblname.setBorder(new javax.swing.border.MatteBorder(null));
        jDesktopPane1.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 170, 30));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(StudentTable);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 490, 290));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Archive");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 230, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Add Subject");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 110, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Add Units");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 110, -1));

        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 150, 40));

        SEARCH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jDesktopPane1.add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 770));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        // 2. Check if the user clicked "Yes"
        if (response == javax.swing.JOptionPane.YES_OPTION) {
        // Go back to login screen
        login lg = new login();
        lg.setVisible(true);

        // Close this Student Management window
        this.dispose();
        }
        // If they click "No", the dialog simply closes and nothing happens
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // 1. Create the Student Management frame
    Studentmanagement sm = new Studentmanagement();
    
    // 2. Make it visible
    sm.setVisible(true);
    
    // 3. Close the current Subject Management frame
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // Calling the same logic as the button
        SEARCHActionPerformed(evt);
    }//GEN-LAST:event_SearchBarActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed

    }//GEN-LAST:event_SEARCHActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// 1. Collect inputs for all fields in your subjects DB
    String code = javax.swing.JOptionPane.showInputDialog(this, "Enter Subject Code:");
    String title = javax.swing.JOptionPane.showInputDialog(this, "Enter Subject Title:");
    String units = javax.swing.JOptionPane.showInputDialog(this, "Enter Units:");
    String teacher = javax.swing.JOptionPane.showInputDialog(this, "Enter Assigned Teacher:");
    String semester = javax.swing.JOptionPane.showInputDialog(this, "Enter Semester (e.g., 1st/2nd):");
    String schoolYear = javax.swing.JOptionPane.showInputDialog(this, "Enter School Year (e.g., 2023-2024):");

    // 2. Validate that inputs are not null (user didn't click cancel)
    if (code != null && title != null && units != null && teacher != null && semester != null && schoolYear != null) {
        config.spconfig conf = new config.spconfig();
        
        // 3. SQL matches your subject table: code, title, units, assigned_teache, semester, school_year
        String sql = "INSERT INTO subjects (code, title, units, assigned_teache, semester, school_year) VALUES (?, ?, ?, ?, ?, ?)";
        
        // 4. Save the record with all collected variables
        conf.addRecord(sql, code, title, units, teacher, semester, schoolYear);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Subject Added Successfully!");
        showSubjectData(); // Refresh table
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Action cancelled or incomplete data.");
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// Usually, units are added to a specific subject. 
    // This logic updates units for a selected subject in the table.
    int selectedRow = StudentTable.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a subject from the table first.");
        return;
    }
    
    String id = StudentTable.getValueAt(selectedRow, 0).toString();
    String newUnits = javax.swing.JOptionPane.showInputDialog(this, "Enter New Units count:");
    
    if (newUnits != null) {
        config.spconfig conf = new config.spconfig();
        String sql = "UPDATE subjects SET units = ? WHERE subject_id = ?";
        // You'll need to add an updateRecord method to spconfig or use a raw connection
        conf.addRecord(sql, newUnits, id); 
        showSubjectData();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void subjectmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectmanagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectmanagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SEARCH;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel name;
    private javax.swing.JButton subjectmanagement;
    // End of variables declaration//GEN-END:variables
}
