/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher;


import admin.Studentmanagement;
import student.login;

/**
 *
 * @author NJ
 */
public class teacherdashboard extends javax.swing.JFrame {

    /**
     * Creates new form teacherdashboard
     */
    public teacherdashboard() {
        initComponents();
        displayMyStudents();
    }
    private void displayMyStudents() {
   String teacherName = lblname.getText().trim(); 

    // IMPORTANT: Your DB uses 'assigned_teache' (missing the 'r')
    String sql = "SELECT student_name AS 'Student Name', title AS 'Subject', student_id AS 'ID' "
               + "FROM subjects "
               + "WHERE assigned_teache = '" + teacherName + "'";
    
    config.spconfig conf = new config.spconfig();
    conf.displayData(sql, StudentTable);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        subjectmanagement = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        SearchBar = new javax.swing.JTextField();
        SEARCH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 51, 0));
        jButton10.setText("Logout");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 120, 30));

        subjectmanagement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subjectmanagement.setText("Student Grading");
        subjectmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectmanagementActionPerformed(evt);
            }
        });
        getContentPane().add(subjectmanagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 230, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Enrolled Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 230, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Portal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/iconify-icon.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        name.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 100, 10));

        lblname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblname.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 170, 30));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(StudentTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 490, 290));

        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 150, 40));

        SEARCH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        getContentPane().add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButton1.setText("Edit Grades");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        // 2. Check if the user clicked "Yes"
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            // Go back to login screen
            login lg = new login();
            lg.setVisible(true);

            // Close this Student Management window
            this.dispose();
        }
        // If they click "No", the dialog simply closes and nothing happens
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Create the Student Management frame
        enrolledstudent sm = new enrolledstudent();

        // 2. Make it visible
        sm.setVisible(true);

        // 3. Close the current Subject Management frame
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // Calling the same logic as the button
        SEARCHActionPerformed(evt);
    }//GEN-LAST:event_SearchBarActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
String find = SearchBar.getText().trim();
    // Use the label name directly to ensure it matches the 'ada' record in your DB
    String teacherName = lblname.getText().trim(); 
    
    // We query the 'subjects' table because it has the student_name and assigned_teache columns
    String sql = "SELECT student_id AS 'ID', student_name AS 'Student Name', title AS 'Subject' "
               + "FROM subjects "
               + "WHERE assigned_teache = '" + teacherName + "' "
               + "AND (student_name LIKE '%" + find + "%' OR title LIKE '%" + find + "%')";
    
    config.spconfig conf = new config.spconfig();
    conf.displayData(sql, StudentTable);
    }//GEN-LAST:event_SEARCHActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
int row = StudentTable.getSelectedRow();
    
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a student to grade first!");
        return;
    }

    // Get info from your table rows based on the display query above
    String sName = StudentTable.getValueAt(row, 0).toString();  // Student Name
    String sSubject = StudentTable.getValueAt(row, 1).toString(); // Subject
    String sID = StudentTable.getValueAt(row, 2).toString();      // Student ID

    try {
        double p = Double.parseDouble(javax.swing.JOptionPane.showInputDialog("Enter Prelim:"));
        double m = Double.parseDouble(javax.swing.JOptionPane.showInputDialog("Enter Midterm:"));
        double f = Double.parseDouble(javax.swing.JOptionPane.showInputDialog("Enter Final:"));
        
        double avg = (p + m + f) / 3;
        String rem = (avg >= 75) ? "Passed" : "Failed";

        // This SQL matches your 8-column 'grades' table structure
        String sql = "INSERT INTO grades (student_name, subject_title, prelim, midterm, final_grade, average, remarks, student_id) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        
        config.spconfig conf = new config.spconfig();
        conf.addRecord(sql, sName, sSubject, p, m, f, avg, rem, sID);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Grade successfully saved for ID: " + sID);
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter numeric grades only.");
    }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void subjectmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectmanagementActionPerformed
   
    }//GEN-LAST:event_subjectmanagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherdashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SEARCH;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel name;
    private javax.swing.JButton subjectmanagement;
    // End of variables declaration//GEN-END:variables

    private void showSubjectData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
